# Codeship specific docker compose file
# This should be virtually the same on every project, although you may need to change the node version for your project
# NEVER use this compose file for production builds
# Caching is done against the develop branch to help speed up CI tests

version: "2"

services:

  dmtdb:
    image: mariadb:latest
    #cached: true
    ports:
      # Map this dynamically on the ci, as parallel builds require it
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=site
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass

  app:
    build: .
    #cached: true
    links:
      - mariadb
    ports:
      - "8000"
